---
- name: Create an EC2 key
  amazon.aws.ec2_key:
    name: "{{ ec2_params.key_name }}"
    region: "{{ ec2_params.region }}"
    key_material: "{{ lookup('file', '~/.ssh/gl_ansible_key.pub') }}"
  register: ec2_key

- name: Create and launch EC2 instances
  amazon.aws.ec2:
    key_name: "{{ ec2_params.key_name }}"
    group: "{{ ec2_params.security_group_name }}"
    instance_type: "{{ ec2_params.instance_type }}"
    image: "{{ ec2_params.image }}"
    wait: yes
    region: "{{ ec2_params.region }}"
    count: "{{ ec2_params.count }}"
    vpc_subnet_id: "{{ ec2_params.subnet }}"
    assign_public_ip: yes
  register: ec2

- name: Add created EC2 instances to groups
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groupname: "{{ inventory_groups[index] }}"
  loop: "{{ ec2.instances }}"
  loop_control:
    index_var: index

- name: Add created EC2 instances to an inventory template file
  template:
    src: roles/create_aws_ec2/templates/inventory.j2
    dest: inventory

#- name: Add created EC2 instances to known_hosts
#  known_hosts:
#    name: "{{ item.public_dns_name }}"
#    key: "{{ lookup('file', '~/.ssh/gl_ansible_key.pub') }}"
#  loop: "{{ ec2.instances }}"

- name: Wait for SSH connection
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
                delay=100
                timeout=600
  with_items: "{{ ec2.instances }}"
